name = "bramble"
compatibility_date = "2026-05-03"
compatibility_flags = ["nodejs_als"]
pages_build_output_dir = ".svelte-kit/cloudflare"

# KV namespace for session metadata and votes.
# `preview_id` is used by `wrangler pages dev` for local development.
[[kv_namespaces]]
binding = "VOTES"
id = "bfb9d2ff18b14322b8a4e8cc4929c389"
preview_id = "ccd8f64b574a4a61b3d4bead2e47af67"
